### ISSUE TITLE
Error Upgrading to D8.4.0

### ISSUE THREAD

**Issue by maxilein007** [dpi/veoa#2]
update.php on UPgrading from D 8.3.7  to D8.4.0 gives the following message:
The module is not installed (maybe it was in the past).
 
Update revision_metadata_fields

    Failed: Drupal\Component\Plugin\Exception\PluginNotFoundException: The "veoa_entity_access_operation" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 52 of .../web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

**Comment by dpi** [comment]
Can I get a stack trace please.

**Comment by maxilein007** [comment]
How would I get that?

**Comment by dpi** [comment]
Cannot repro
